name: solanatestnet
displayName: Solana Testnet
domainId: 1399811150
chainId: 1399811150
isTestnet: true
mailbox: 75HBBLae3ddeneJVrZeyrDfv6vb7SMC3aCpBucSXS5aR
nativeToken:
  decimals: 9
  name: SOL
  symbol: SOL
protocol: sealevel