[package]
description = "Generic per-precompile sequencing-data registry for the Relay Chain"
edition = { workspace = true }
license = { workspace = true }
name = "sequencing-registry"
publish = false
repository = { workspace = true }
rust-version = { workspace = true }
version = "1.0.0"

[dependencies]
alloy-primitives = { workspace = true, features = ["borsh"] }
borsh = { workspace = true }
bytes = { workspace = true }
sov-modules-api = { workspace = true }
tracing = { workspace = true }

[features]
default = []
native = ["sov-modules-api/native"]
