[workspace]

resolver = "2"

members = [
  "crates/rollup",
  "crates/stf",
  "crates/stf/stf-declaration",
  "crates/utils/node-discovery",
  "crates/precompiles/price-oracle",
  "crates/shared/price-oracle-ipc",
  "examples/value-setter",
]
default-members = ["crates/rollup", "crates/utils/node-discovery"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "Sovereign Permissionless Commercial License"
authors = ["Sovereign Labs <info@sovereign.xyz>"]
repository = "https://github.com/Sovereign-Labs/rollup-starter"
publish = false
rust-version = "1.93"

[workspace.dependencies]
sov-address = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df", features = [
  "evm",
] }
sov-accounts = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-api-spec = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-attester-incentives = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-chain-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-bank = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-blob-storage = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-paymaster = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-capabilities = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-celestia-adapter = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-cli = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-db = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-hyperlane-integration = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df", features = [
  "evm",
] }
sov-test-state-consistency = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-kernels = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-ledger-apis = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-mock-da = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-mock-zkvm = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-modules-api = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-modules-rollup-blueprint = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-modules-stf-blueprint = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-uniqueness = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-operator-incentives = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-prover-incentives = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-revenue-share = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-rollup-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-rollup-full-node-interface = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-sequencer = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-shutdown = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-sequencer-registry = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-state = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-stf-runner = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-test-utils = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-rollup-apis = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-universal-wallet = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-zkvm-utils = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-build = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-ethereum = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-evm = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-eip712-auth = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-rest-utils = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-proxy-utils = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df" }
sov-metrics = { git = "https://github.com/Sovereign-Labs/sovereign-sdk.git", rev = "2d7af7fe25001734daaa95509e487566180650df", features = ["native"] }


stf-starter = { path = "./crates/stf", default-features = false }
stf-starter-declaration = { path = "./crates/stf/stf-declaration", default-features = false }
node-discovery = { path = "./crates/utils/node-discovery", default-features = false }
price-oracle = { path = "./crates/precompiles/price-oracle", default-features = false }
price-oracle-ipc = { path = "./crates/shared/price-oracle-ipc", default-features = false }
value-setter = { path = "./examples/value-setter" }
strum = { version = "0.28", features = ["derive"] }

alloy = { version = "1.0.41", default-features = false, features = ["std", "essentials"] }
alloy-consensus = { version = "1.1.0", default-features = false }
alloy-primitives = { version = "1.4.1", default-features = false }
alloy-rpc-types = { version = "1.0.41", default-features = false, features = ["eth"] }
alloy-sol-types = { version = "1.4.1", default-features = false }
axum = { version = "0.8.8", default-features = false }
serde = { version = "1.0.192", features = ["derive", "rc"] }
serde_json = { version = "1.0" }

sha2 = { version = "=0.10.9", default-features = false }

schemars = { version = "1.2", features = ["derive"] }
anyhow = { version = "1.0.95" }
clap = { version = "4.4.10", features = ["derive"] }
async-trait = "0.1.71"
borsh = { version = "1", features = ["rc", "bytes"] }
bytes = { version = "1", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tracing-appender = "0.2"
tokio = { version = "1", features = ["full"] }
lazy_static = "1.5.0"
parking_lot = { version = "0.12", default-features = false }
tempfile = "3.20"
jsonrpsee = { version = "0.26", features = ["jsonrpsee-types"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }

# [patch."https://github.com/paradigmxyz/reth"]
# reth-rpc-eth-types = { path = "/home/gentoo/work/sovereign/reth/crates/rpc/rpc-eth-types" }
