.PHONY: help check lint clean clean-db start-obs stop-obs

# Should remain at the top, otherwise `make` won't print help
help: ## Display this help message
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

check: ## Run cargo check here and in for all ZKVM Provers. Useful for updating Cargo.lock
	SKIP_GUEST_BUILD=1 cargo check

lint: ## Run fmt, check and clippy with the most important feature combinations
	SKIP_GUEST_BUILD=1 cargo fmt --all -- --check
	SKIP_GUEST_BUILD=1 cargo check
	SKIP_GUEST_BUILD=1 cargo clippy
	zepter  # Run it several times, as fix from the first run can uncover other issues
	zepter

clean: clean-db
clean: ## Clean all builds and artifacts and databases
	@cargo clean
	rm -rf examples/starter-js/node_modules
	rm -rf examples/privy/node_modules
	rm -f crates/stf/runtime_call.json
	rm -f crates/stf/autogenerated.inc.rs
	rm -f examples/starter-js/src/types.ts
	$(MAKE) -C integrations clean

clean-db: ## Clean all databases
	rm -rf rollup-state/rollup-starter-data-celestia

start-obs:  ## Start observability stack
	./scripts/start_observability.sh

stop-obs:  ## Stop observability stack
	./scripts/stop_observability.sh
