---
sovstarter:
  name: sovstarter
  displayName: Sov Starter
  domainId: 5577
  # Taken from `../../../constants.toml
  chaindId: 4321
  isTestnet: true
  nativeToken:
    decimals: 8
    name: SovToken
    symbol: sov
  protocol: sovereign
  rpcUrls:
    - http: http://host.docker.internal:12346
solanatestnet:
  name: solanatestnet
  displayName: Solana Testnet
  domainId: 1399811150
  chainId: 1399811150
  isTestnet: true
  # testnet mailbox, from here https://docs.hyperlane.xyz/docs/reference/addresses/deployments/mailbox
  mailbox: 75HBBLae3ddeneJVrZeyrDfv6vb7SMC3aCpBucSXS5aR
  nativeToken:
    decimals: 9
    name: SOL
    symbol: SOL
  protocol: sealevel
  rpcUrls:
    - http: https://api.testnet.solana.com
# Local anvil
ethtest:
  chainId: 31337
  displayName: EthTest
  domainId: 31337_90210
  isTestnet: true
  name: ethtest
  nativeToken:
    decimals: 18
    name: Ether
    symbol: ETH
  protocol: ethereum
  rpcUrls:
    - http: http://host.docker.internal:8545
# TODO: Sepolia eth testnet
