[oracle]
enabled = true
require_sources = false

[[oracle.source]]
name = "chainlink"
socket_address = "127.0.0.1:9801"
transport = "tcp"

# [[oracle.source]]
# name = "pyth"
# socket_address = "127.0.0.1:9802"
# transport = "tcp"

# [[oracle.source]]
# name = "redstone"
# socket_address = "127.0.0.1:9803"
# transport = "tcp"
