// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script} from "forge-std/Script.sol";
import {console2} from "forge-std/console2.sol";
import {SimpleContract} from "../src/SimpleContract.sol";
import {Create2Factory} from "../src/Create2Factory.sol";

contract DeploymentTests is Script {
    function run() public {
        vm.startBroadcast();

        console2.log("=== Phase 1: Deployment Tests ===\n");

        // Test 1: Simple deployment
        testSimpleDeployment();

        // Test 2: CREATE2 deployment
        testCreate2Deployment();

        // Test 3: Large contract (near 512 KiB)
        testLargeContract();

        vm.stopBroadcast();
    }

    function testSimpleDeployment() internal {
        console2.log("--- Test 1: Simple Contract Deployment ---");
        uint256 gasBefore = gasleft();

        SimpleContract simple = new SimpleContract();

        uint256 gasUsed = gasBefore - gasleft();
        console2.log("Contract deployed at:", address(simple));
        console2.log("Gas used:", gasUsed);
        console2.log("Bytecode size:", address(simple).code.length, "bytes");
        console2.log("");
    }

    function testCreate2Deployment() internal {
        console2.log("--- Test 2: CREATE2 Deployment ---");

        // Deploy factory
        uint256 gasFactory = gasleft();
        Create2Factory factory = new Create2Factory();
        uint256 gasFactoryUsed = gasFactory - gasleft();

        console2.log("Factory deployed at:", address(factory));
        console2.log("Factory deployment gas:", gasFactoryUsed);

        // Get bytecode for deployment
        bytes memory bytecode = type(SimpleContract).creationCode;
        bytecode = abi.encodePacked(bytecode, abi.encode(uint256(42)));
        bytes32 bytecodeHash = keccak256(bytecode);

        // Generate random salt for idempotency (based on timestamp + tx.origin)
        bytes32 salt = keccak256(abi.encodePacked(block.timestamp, tx.origin, "create2"));
        console2.log("Using salt:", uint256(salt));

        // Predict address
        address predicted = factory.computeAddress(salt, bytecodeHash);
        console2.log("Predicted address:", predicted);

        // Deploy via CREATE2
        uint256 gasDeploy = gasleft();
        address deployed = factory.deploy(salt, bytecode);
        uint256 gasDeployUsed = gasDeploy - gasleft();

        require(predicted == deployed, "Addresses should match");
        console2.log("Deployed address:", deployed);
        console2.log("CREATE2 gas used:", gasDeployUsed);
        console2.log("");
    }

    function testLargeContract() internal {
        console2.log("--- Test 3: Large Contract (near 512 KiB) ---");

        // Generate bytecode approaching 512 KiB limit (524288 bytes)
        // Custom EVM allows max 512 KiB deployed bytecode
        bytes memory largeBytecode = generateLargeBytecode(520000);

        console2.log("Generated bytecode size:", largeBytecode.length, "bytes");
        console2.log("Size in KiB:", largeBytecode.length / 1024);

        uint256 gasBefore = gasleft();
        address deployed;

        assembly {
            deployed := create(0, add(largeBytecode, 0x20), mload(largeBytecode))
        }

        uint256 gasUsed = gasBefore - gasleft();

        if (deployed == address(0)) {
            console2.log("Deployment FAILED");
        } else {
            console2.log("Contract deployed at:", deployed);
            console2.log("Deployed bytecode size:", deployed.code.length, "bytes");
            console2.log("Deployed size in KiB:", deployed.code.length / 1024);
        }
        console2.log("Gas used:", gasUsed);
        console2.log("");
    }

    /**
     * @notice Generate large bytecode for testing size limits
     * @dev Creates valid bytecode that returns empty data
     * Format: PUSH1 0x00 DUP1 RETURN (returns 0 bytes)
     * Then pads with JUMPDEST (0x5b) to reach target size
     */
    function generateLargeBytecode(uint256 targetSize) internal pure returns (bytes memory) {
        // Runtime code: PUSH1 0 DUP1 RETURN = 0x60008051f3
        bytes memory runtime = hex"60008051f3";

        // Pad with JUMPDEST opcodes (0x5b) to reach target size
        bytes memory paddedRuntime = new bytes(targetSize);
        for (uint256 i = 0; i < runtime.length; i++) {
            paddedRuntime[i] = runtime[i];
        }
        for (uint256 i = runtime.length; i < targetSize; i++) {
            paddedRuntime[i] = 0x5b; // JUMPDEST opcode
        }

        return paddedRuntime;
    }
}
