#![allow(unused_doc_comments)]
//! This module implements `Runtime` trait and ensures that it uses correct `CHAIN_HASH`
use sov_address::{EthereumAddress, EvmCryptoSpec, FromVmAddress};
use sov_evm::{Eip712Authenticator, Eip712AuthenticatorTrait, SchemaProvider};
use sov_hyperlane_integration::HyperlaneAddress;
use sov_modules_api::capabilities::TransactionAuthenticator;
#[cfg(feature = "native")]
use sov_modules_api::prelude::*;
use sov_modules_api::OperatingMode;
use sov_modules_api::Spec;
use sov_rollup_interface::da::DaSpec;

pub use stf_starter_declaration::GenesisConfig;
pub use stf_starter_declaration::Mailbox;
use stf_starter_declaration::Runtime as RuntimeInner;
pub use stf_starter_declaration::RuntimeCall;
#[cfg(feature = "native")]
pub use stf_starter_declaration::RuntimeSubcommand;

// CHAIN_HASH and Schema are generated during build time.
// This allows make sure that Runtime can be authenticated in ZKVM guest.
mod __generated {
    include!("../.artifacts/autogenerated.rs");
}

#[derive(Clone, Default)]
pub struct Runtime<S: Spec>(pub(crate) RuntimeInner<S>)
where
    <S as Spec>::Address: HyperlaneAddress;

impl<S: Spec> SchemaProvider for Runtime<S>
where
    <S as Spec>::Address: HyperlaneAddress,
{
    const SCHEMA_BORSH: &'static [u8] = __generated::SCHEMA_BORSH;
}

impl<S: Spec<CryptoSpec = EvmCryptoSpec>> Eip712AuthenticatorTrait<S> for Runtime<S>
where
    S::Da: DaSpec,
    S::Address: HyperlaneAddress + FromVmAddress<EthereumAddress>,
{
    fn add_eip712_auth(
        tx: sov_modules_api::RawTx,
    ) -> <Self::Auth as TransactionAuthenticator<S>>::Input {
        sov_evm::Eip712AuthenticatorInput::Eip712(tx)
    }
}

impl<S: Spec<CryptoSpec = EvmCryptoSpec>> sov_modules_stf_blueprint::Runtime<S> for Runtime<S>
where
    S::Da: DaSpec,
    S::Address: HyperlaneAddress + FromVmAddress<EthereumAddress>,
{
    // Make runtime authenticated.
    const CHAIN_HASH: [u8; 32] = __generated::CHAIN_HASH;

    type GenesisConfig = GenesisConfig<S>;

    #[cfg(feature = "native")]
    type GenesisInput = std::path::PathBuf;

    type Auth = Eip712Authenticator<S, Self, Self>;

    #[cfg(feature = "native")]
    fn endpoints(api_state: sov_modules_api::rest::ApiState<S>) -> sov_modules_api::NodeEndpoints {
        use ::sov_modules_api::rest::HasRestApi;
        use ::sov_rollup_apis::endpoints::dedup::{DeDupEndpoint, SovereignDeDupEndpoint};
        use ::sov_rollup_apis::endpoints::schema::{SchemaEndpoint, StandardSchemaEndpoint};

        let axum_router = Self::default().0.rest_api(api_state.clone());
        // Provide an endpoint to return dedup information associated with addresses.
        // Since our runtime is using the uniqueness module, we can use the provided `SovereignDeDupEndpoint` implementation.
        let dedup_endpoint = SovereignDeDupEndpoint::new(api_state.clone());
        let axum_router = axum_router.merge(dedup_endpoint.axum_router());
        let axum_router = axum_router.merge(sov_rollup_apis::endpoints::constants::axum_router());

        let schema_endpoint = StandardSchemaEndpoint::new(
            &serde_json::from_str(__generated::SCHEMA_JSON)
                .expect("Failed to deserialize schema json"),
            Self::CHAIN_HASH.into(),
        )
        .expect("Failed to initialize StandardSchemaEndpoint");
        let axum_router = axum_router.merge(schema_endpoint.axum_router());

        // Get the existing RPC methods from the runtime
        let mut jsonrpsee_module = stf_starter_declaration::get_rpc_methods::<S>(api_state);

        // Create minimal EVM RPC module for EIP712 signing compatibility
        // (this should be removed if a full EVM module is integrated)
        let mut minimal_evm_rpc = jsonrpsee::RpcModule::new(());

        // These two methods are needed for metamask to validate the chain ID, otherwise it refuses
        // to sign the EIP712 message
        minimal_evm_rpc
            .register_method("eth_chainId", |_, _, _| {
                let chain_id = config_value!("CHAIN_ID");
                Ok::<_, jsonrpsee::types::ErrorObjectOwned>(format!("0x{chain_id:x}"))
            })
            .expect("Failed to register eth_chainId");
        minimal_evm_rpc
            .register_method("net_version", |_, _, _| {
                let chain_id = config_value!("CHAIN_ID");
                Ok::<_, jsonrpsee::types::ErrorObjectOwned>(chain_id.to_string())
            })
            .expect("Failed to register net_version");

        // And the next two methods are necessary for Metamask to consider the RPC endpoint "live"
        // - without them it reports a connection error, making the network non-functional. But the
        // data does not matter for signing offchain messages, so dummy data is sufficient to keep
        // Metamask happy.
        minimal_evm_rpc
            .register_method("eth_blockNumber", |_, _, _| {
                // Return a placeholder block number since we don't have full EVM state
                // MetaMask just needs this to return successfully
                Ok::<_, jsonrpsee::types::ErrorObjectOwned>("0x1".to_string())
            })
            .expect("Failed to register eth_blockNumber");
        minimal_evm_rpc
            .register_method("eth_getBlockByNumber", |_, _, _| {
                // Return a minimal block structure
                let block = serde_json::json!({
                    "number": "0x1",
                    "hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "timestamp": "0x0",
                    "gasLimit": "0x1c9c380",
                    "gasUsed": "0x0",
                    "transactions": []
                });
                Ok::<_, jsonrpsee::types::ErrorObjectOwned>(block)
            })
            .expect("Failed to register eth_getBlockByNumber");

        // Merge the minimal EVM RPC methods into the main module
        jsonrpsee_module.merge(minimal_evm_rpc).expect(
            "Failed to merge minimal EVM RPC - remove this block if full EVM module is added",
        );

        sov_modules_api::NodeEndpoints {
            axum_router,
            jsonrpsee_module,
            background_handles: Vec::new(),
        }
    }

    #[cfg(feature = "native")]
    fn genesis_config(input: &Self::GenesisInput) -> Result<Self::GenesisConfig, anyhow::Error> {
        let contents = std::fs::read(input)?;
        Ok(serde_json::from_slice(&contents)?)
    }

    fn operating_mode(genesis: &Self::GenesisConfig) -> OperatingMode {
        genesis.chain_state.operating_mode
    }

    fn wrap_call(
        auth_data: <Self::Auth as TransactionAuthenticator<S>>::Decodable,
    ) -> Self::Decodable {
        auth_data
    }

    fn allow_unregistered_tx(call: &Self::Decodable) -> bool {
        matches!(
            call,
            Self::Decodable::SequencerRegistry(
                sov_sequencer_registry::CallMessage::Register { .. }
            )
        )
    }
}
